In [4]:
import numpy as np
m,n=[int(i) for i in input("Enter rows and columns of matrix1").split()]
print("Enter the entries in a single line: ")
entries=[int(i) for i in input().split()]
A= np.array(entries).reshape(m, n)
m,n=[int(i) for i in input("Enter rows and columns of matrix2").split()]
print("Enter the entries in a single line: ")
entries=[int(i) for i in input().split()]
B= np.array(entries).reshape(m, n)
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Dot product of A and B:")
print(np.dot(A,B))
print("Transpose of A:")
print(np.transpose(A))
print("Transpose of B:")
print(np.transpose(B))
print("Trace of A:")
print(np.trace(A))
print("Trace of B:")
print(np.trace(B))
print("Rank of the matrix A",np.linalg.matrix_rank(A))
print("Rank of the matrix B",np.linalg.matrix_rank(B))
detA = np.linalg.det(A)
detB = np.linalg.det(B)
print("Determinant of the matrix A ",int(detA))
print("Determinant of the matrix B ",int(detB))
print("Inverse of the matrix A ")
print(np.linalg.inv(A))
print("Inverse of the matrix B ")
print(np.linalg.inv(B))
eigenValueA,eigenVectorA=np.linalg.eig(A)
eigenValueB,eigenVectorB=np.linalg.eig(B)
print("Eigen values of A ",eigenValueA)
print("Eigen vectors of A ",eigenVectorA)
print("Eigen values of B ",eigenValueB)
print("Eigen vectors of B ",eigenVectorB)


Enter rows and columns of matrix12 2
Enter the entries in a single line: 
1 2 3 4
Enter rows and columns of matrix22 2
Enter the entries in a single line: 
7 6 5 4
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[7 6]
 [5 4]]
Dot product of A and B:
[[17 14]
 [41 34]]
Transpose of A:
[[1 3]
 [2 4]]
Transpose of B:
[[7 5]
 [6 4]]
Trace of A:
5
Trace of B:
11
Rank of the matrix A 2
Rank of the matrix B 2
Determinant of the matrix A  -2
Determinant of the matrix B  -1
Inverse of the matrix A 
[[-2.   1. ]
 [ 1.5 -0.5]]
Inverse of the matrix B 
[[-2.   3. ]
 [ 2.5 -3.5]]
Eigen values of A  [-0.37228132  5.37228132]
Eigen vectors of A  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Eigen values of B  [11.17890835 -0.17890835]
Eigen vectors of B  [[ 0.82058481 -0.64129241]
 [ 0.57152478  0.76729658]]
